// Banco gerado por scripts/build_lexicon.py. Palavras novas, sem acento e só com sílabas consoante-vogal.
(function (root) {
  'use strict';
  const extras = [
    ['bode', 'BODE', ['BO', 'DE'], 'Desenho de bode', [0, 1]],
    ['mula', 'MULA', ['MU', 'LA'], 'Desenho de mula', [0, 1]],
    ['paca', 'PACA', ['PA', 'CA'], 'Desenho de paca', [0, 1]],
    ['tatu', 'TATU', ['TA', 'TU'], 'Desenho de tatu', [0, 1]],
    ['puma', 'PUMA', ['PU', 'MA'], 'Desenho de puma', [0, 1]],
    ['mico', 'MICO', ['MI', 'CO'], 'Desenho de mico', [0, 1]],
    ['juba', 'JUBA', ['JU', 'BA'], 'Desenho de juba', [0, 1]],
    ['gata', 'GATA', ['GA', 'TA'], 'Desenho de gata', [0, 1]],
    ['galo', 'GALO', ['GA', 'LO'], 'Desenho de galo', [0, 1]],
    ['peru', 'PERU', ['PE', 'RU'], 'Desenho de peru', [0, 1]],
    ['jacu', 'JACU', ['JA', 'CU'], 'Desenho de jacu', [0, 1]],
    ['cuco', 'CUCO', ['CU', 'CO'], 'Desenho de cuco', [0, 1]],
    ['boto', 'BOTO', ['BO', 'TO'], 'Desenho de boto', [0, 1]],
    ['siri', 'SIRI', ['SI', 'RI'], 'Desenho de siri', [0, 1]],
    ['lula', 'LULA', ['LU', 'LA'], 'Desenho de lula', [0, 1]],
    ['bolo', 'BOLO', ['BO', 'LO'], 'Desenho de bolo', [0, 1]],
    ['bala', 'BALA', ['BA', 'LA'], 'Desenho de bala', [0, 1]],
    ['sopa', 'SOPA', ['SO', 'PA'], 'Desenho de sopa', [0, 1]],
    ['jaca', 'JACA', ['JA', 'CA'], 'Desenho de jaca', [0, 1]],
    ['lima', 'LIMA', ['LI', 'MA'], 'Desenho de lima', [0, 1]],
    ['figo', 'FIGO', ['FI', 'GO'], 'Desenho de figo', [0, 1]],
    ['nabo', 'NABO', ['NA', 'BO'], 'Desenho de nabo', [0, 1]],
    ['nata', 'NATA', ['NA', 'TA'], 'Desenho de nata', [0, 1]],
    ['fava', 'FAVA', ['FA', 'VA'], 'Desenho de fava', [0, 1]],
    ['doce', 'DOCE', ['DO', 'CE'], 'Desenho de doce', [0, 1]],
    ['goma', 'GOMA', ['GO', 'MA'], 'Desenho de goma', [0, 1]],
    ['gema', 'GEMA', ['GE', 'MA'], 'Desenho de gema', [0, 1]],
    ['papa', 'PAPA', ['PA', 'PA'], 'Desenho de papa', [0, 1]],
    ['caju', 'CAJU', ['CA', 'JU'], 'Desenho de caju', [0, 1]],
    ['soja', 'SOJA', ['SO', 'JA'], 'Desenho de soja', [0, 1]],
    ['cuca', 'CUCA', ['CU', 'CA'], 'Desenho de cuca', [0, 1]],
    ['tutu', 'TUTU', ['TU', 'TU'], 'Desenho de tutu', [0, 1]],
    ['favo', 'FAVO', ['FA', 'VO'], 'Desenho de favo', [0, 1]],
    ['nuca', 'NUCA', ['NU', 'CA'], 'Desenho de nuca', [0, 1]],
    ['pelo', 'PELO', ['PE', 'LO'], 'Desenho de pelo', [0, 1]],
    ['pele', 'PELE', ['PE', 'LE'], 'Desenho de pele', [0, 1]],
    ['colo', 'COLO', ['CO', 'LO'], 'Desenho de colo', [0, 1]],
    ['sola', 'SOLA', ['SO', 'LA'], 'Desenho de sola', [0, 1]],
    ['rabo', 'RABO', ['RA', 'BO'], 'Desenho de rabo', [0, 1]],
    ['pata', 'PATA', ['PA', 'TA'], 'Desenho de pata', [0, 1]],
    ['mesa', 'MESA', ['ME', 'SA'], 'Desenho de mesa', [0, 1]],
    ['sala', 'SALA', ['SA', 'LA'], 'Desenho de sala', [0, 1]],
    ['vaso', 'VASO', ['VA', 'SO'], 'Desenho de vaso', [0, 1]],
    ['vela', 'VELA', ['VE', 'LA'], 'Desenho de vela', [0, 1]],
    ['teto', 'TETO', ['TE', 'TO'], 'Desenho de teto', [0, 1]],
    ['pote', 'POTE', ['PO', 'TE'], 'Desenho de pote', [0, 1]],
    ['copo', 'COPO', ['CO', 'PO'], 'Desenho de copo', [0, 1]],
    ['capa', 'CAPA', ['CA', 'PA'], 'Desenho de capa', [0, 1]],
    ['fita', 'FITA', ['FI', 'TA'], 'Desenho de fita', [0, 1]],
    ['lupa', 'LUPA', ['LU', 'PA'], 'Desenho de lupa', [0, 1]],
    ['tubo', 'TUBO', ['TU', 'BO'], 'Desenho de tubo', [0, 1]],
    ['taco', 'TACO', ['TA', 'CO'], 'Desenho de taco', [0, 1]],
    ['cubo', 'CUBO', ['CU', 'BO'], 'Desenho de cubo', [0, 1]],
    ['foto', 'FOTO', ['FO', 'TO'], 'Desenho de foto', [0, 1]],
    ['cabo', 'CABO', ['CA', 'BO'], 'Desenho de cabo', [0, 1]],
    ['muro', 'MURO', ['MU', 'RO'], 'Desenho de muro', [0, 1]],
    ['lona', 'LONA', ['LO', 'NA'], 'Desenho de lona', [0, 1]],
    ['saco', 'SACO', ['SA', 'CO'], 'Desenho de saco', [0, 1]],
    ['bule', 'BULE', ['BU', 'LE'], 'Desenho de bule', [0, 1]],
    ['cano', 'CANO', ['CA', 'NO'], 'Desenho de cano', [0, 1]],
    ['cola', 'COLA', ['CO', 'LA'], 'Desenho de cola', [0, 1]],
    ['vara', 'VARA', ['VA', 'RA'], 'Desenho de vara', [0, 1]],
    ['rolo', 'ROLO', ['RO', 'LO'], 'Desenho de rolo', [0, 1]],
    ['tela', 'TELA', ['TE', 'LA'], 'Desenho de tela', [0, 1]],
    ['piso', 'PISO', ['PI', 'SO'], 'Desenho de piso', [0, 1]],
    ['laje', 'LAJE', ['LA', 'JE'], 'Desenho de laje', [0, 1]],
    ['lago', 'LAGO', ['LA', 'GO'], 'Desenho de lago', [0, 1]],
    ['lama', 'LAMA', ['LA', 'MA'], 'Desenho de lama', [0, 1]],
    ['mato', 'MATO', ['MA', 'TO'], 'Desenho de mato', [0, 1]],
    ['neve', 'NEVE', ['NE', 'VE'], 'Desenho de neve', [0, 1]],
    ['bote', 'BOTE', ['BO', 'TE'], 'Desenho de bote', [0, 1]],
    ['jato', 'JATO', ['JA', 'TO'], 'Desenho de jato', [0, 1]],
    ['fone', 'FONE', ['FO', 'NE'], 'Desenho de fone', [0, 1]],
    ['remo', 'REMO', ['RE', 'MO'], 'Desenho de remo', [0, 1]],
    ['cone', 'CONE', ['CO', 'NE'], 'Desenho de cone', [0, 1]],
    ['pino', 'PINO', ['PI', 'NO'], 'Desenho de pino', [0, 1]],
    ['gota', 'GOTA', ['GO', 'TA'], 'Desenho de gota', [0, 1]],
    ['ramo', 'RAMO', ['RA', 'MO'], 'Desenho de ramo', [0, 1]],
    ['gude', 'GUDE', ['GU', 'DE'], 'Desenho de gude', [0, 1]],
    ['vime', 'VIME', ['VI', 'ME'], 'Desenho de vime', [0, 1]],
    ['lodo', 'LODO', ['LO', 'DO'], 'Desenho de lodo', [0, 1]],
    ['doca', 'DOCA', ['DO', 'CA'], 'Desenho de doca', [0, 1]],
    ['copa', 'COPA', ['CO', 'PA'], 'Desenho de copa', [0, 1]],
    ['soda', 'SODA', ['SO', 'DA'], 'Desenho de soda', [0, 1]],
    ['jipe', 'JIPE', ['JI', 'PE'], 'Desenho de jipe', [0, 1]],
    ['feno', 'FENO', ['FE', 'NO'], 'Desenho de feno', [0, 1]],
    ['vala', 'VALA', ['VA', 'LA'], 'Desenho de vala', [0, 1]],
    ['furo', 'FURO', ['FU', 'RO'], 'Desenho de furo', [0, 1]],
    ['lira', 'LIRA', ['LI', 'RA'], 'Desenho de lira', [0, 1]],
    ['ripa', 'RIPA', ['RI', 'PA'], 'Desenho de ripa', [0, 1]],
    ['rodo', 'RODO', ['RO', 'DO'], 'Desenho de rodo', [0, 1]],
    ['toco', 'TOCO', ['TO', 'CO'], 'Desenho de toco', [0, 1]],
    ['toca', 'TOCA', ['TO', 'CA'], 'Desenho de toca', [0, 1]],
    ['tora', 'TORA', ['TO', 'RA'], 'Desenho de tora', [0, 1]],
    ['talo', 'TALO', ['TA', 'LO'], 'Desenho de talo', [0, 1]],
    ['gomo', 'GOMO', ['GO', 'MO'], 'Desenho de gomo', [0, 1]],
    ['seta', 'SETA', ['SE', 'TA'], 'Desenho de seta', [0, 1]],
    ['seda', 'SEDA', ['SE', 'DA'], 'Desenho de seda', [0, 1]],
    ['nota', 'NOTA', ['NO', 'TA'], 'Desenho de nota', [0, 1]],
    ['selo', 'SELO', ['SE', 'LO'], 'Desenho de selo', [0, 1]],
    ['pufe', 'PUFE', ['PU', 'FE'], 'Desenho de pufe', [0, 1]],
    ['jogo', 'JOGO', ['JO', 'GO'], 'Desenho de jogo', [0, 1]],
    ['rifa', 'RIFA', ['RI', 'FA'], 'Desenho de rifa', [0, 1]],
    ['saci', 'SACI', ['SA', 'CI'], 'Desenho de saci', [0, 1]],
    ['lume', 'LUME', ['LU', 'ME'], 'Desenho de lume', [0, 1]],
    ['cuba', 'CUBA', ['CU', 'BA'], 'Desenho de cuba', [0, 1]],
    ['polo', 'POLO', ['PO', 'LO'], 'Desenho de polo', [0, 1]],
    ['fila', 'FILA', ['FI', 'LA'], 'Desenho de fila', [0, 1]],
    ['vila', 'VILA', ['VI', 'LA'], 'Desenho de vila', [0, 1]],
    ['gelo', 'GELO', ['GE', 'LO'], 'Desenho de gelo', [0, 1]],
    ['fada', 'FADA', ['FA', 'DA'], 'Desenho de fada', [0, 1]],
    ['dona', 'DONA', ['DO', 'NA'], 'Desenho de dona', [0, 1]],
    ['mago', 'MAGO', ['MA', 'GO'], 'Desenho de mago', [0, 1]],
    ['bata', 'BATA', ['BA', 'TA'], 'Desenho de bata', [0, 1]],
    ['caco', 'CACO', ['CA', 'CO'], 'Desenho de caco', [0, 1]],
    ['cova', 'COVA', ['CO', 'VA'], 'Desenho de cova', [0, 1]],
    ['dama', 'DAMA', ['DA', 'MA'], 'Desenho de dama', [0, 1]],
    ['dono', 'DONO', ['DO', 'NO'], 'Desenho de dono', [0, 1]],
    ['gola', 'GOLA', ['GO', 'LA'], 'Desenho de gola', [0, 1]],
    ['loja', 'LOJA', ['LO', 'JA'], 'Desenho de loja', [0, 1]],
    ['mama', 'MAMA', ['MA', 'MA'], 'Desenho de mama', [0, 1]],
    ['mata', 'MATA', ['MA', 'TA'], 'Desenho de mata', [0, 1]],
    ['muda', 'MUDA', ['MU', 'DA'], 'Desenho de muda', [0, 1]],
    ['mofo', 'MOFO', ['MO', 'FO'], 'Desenho de mofo', [0, 1]],
    ['mola', 'MOLA', ['MO', 'LA'], 'Desenho de mola', [0, 1]],
    ['pano', 'PANO', ['PA', 'NO'], 'Desenho de pano', [0, 1]],
    ['pico', 'PICO', ['PI', 'CO'], 'Desenho de pico', [0, 1]],
    ['pulo', 'PULO', ['PU', 'LO'], 'Desenho de pulo', [0, 1]],
    ['ralo', 'RALO', ['RA', 'LO'], 'Desenho de ralo', [0, 1]],
    ['rena', 'RENA', ['RE', 'NA'], 'Desenho de rena', [0, 1]],
    ['rubi', 'RUBI', ['RU', 'BI'], 'Desenho de rubi', [0, 1]],
    ['ruga', 'RUGA', ['RU', 'GA'], 'Desenho de ruga', [0, 1]],
    ['silo', 'SILO', ['SI', 'LO'], 'Desenho de silo', [0, 1]],
    ['solo', 'SOLO', ['SO', 'LO'], 'Desenho de solo', [0, 1]],
    ['sono', 'SONO', ['SO', 'NO'], 'Desenho de sono', [0, 1]],
    ['sumo', 'SUMO', ['SU', 'MO'], 'Desenho de sumo', [0, 1]],
    ['tira', 'TIRA', ['TI', 'RA'], 'Desenho de tira', [0, 1]],
    ['topo', 'TOPO', ['TO', 'PO'], 'Desenho de topo', [0, 1]],
    ['vale', 'VALE', ['VA', 'LE'], 'Desenho de vale', [0, 1]],
    ['foco', 'FOCO', ['FO', 'CO'], 'Desenho de foco', [0, 1]],
    ['foro', 'FORO', ['FO', 'RO'], 'Desenho de foro', [0, 1]],
    ['leme', 'LEME', ['LE', 'ME'], 'Desenho de leme', [0, 1]],
    ['pala', 'PALA', ['PA', 'LA'], 'Desenho de pala', [0, 1]],
    ['mina', 'MINA', ['MI', 'NA'], 'Desenho de mina', [0, 1]],
    ['duna', 'DUNA', ['DU', 'NA'], 'Desenho de duna', [0, 1]],
    ['poda', 'PODA', ['PO', 'DA'], 'Desenho de poda', [0, 1]],
    ['diva', 'DIVA', ['DI', 'VA'], 'Desenho de diva', [0, 1]],
    ['pera', 'PERA', ['PE', 'RA'], 'Desenho de pera', [0, 1]],
    ['cana', 'CANA', ['CA', 'NA'], 'Desenho de cana', [0, 1]],
    ['bife', 'BIFE', ['BI', 'FE'], 'Desenho de bife', [0, 1]],
    ['popa', 'POPA', ['PO', 'PA'], 'Desenho de popa', [0, 1]],
    ['sebo', 'SEBO', ['SE', 'BO'], 'Desenho de sebo', [0, 1]],
    ['viga', 'VIGA', ['VI', 'GA'], 'Desenho de viga', [0, 1]],
    ['tuba', 'TUBA', ['TU', 'BA'], 'Desenho de tuba', [0, 1]],
    ['rata', 'RATA', ['RA', 'TA'], 'Desenho de rata', [0, 1]],
    ['gula', 'GULA', ['GU', 'LA'], 'Desenho de gula', [0, 1]],
    ['guri', 'GURI', ['GU', 'RI'], 'Desenho de guri', [0, 1]],
    ['beco', 'BECO', ['BE', 'CO'], 'Desenho de beco', [0, 1]],
    ['gado', 'GADO', ['GA', 'DO'], 'Desenho de gado', [0, 1]],
    ['neto', 'NETO', ['NE', 'TO'], 'Desenho de neto', [0, 1]],
    ['nora', 'NORA', ['NO', 'RA'], 'Desenho de nora', [0, 1]],
    ['tala', 'TALA', ['TA', 'LA'], 'Desenho de tala', [0, 1]],
    ['bica', 'BICA', ['BI', 'CA'], 'Desenho de bica', [0, 1]],
    ['cera', 'CERA', ['CE', 'RA'], 'Desenho de cera', [0, 1]],
    ['duto', 'DUTO', ['DU', 'TO'], 'Desenho de duto', [0, 1]],
    ['gibi', 'GIBI', ['GI', 'BI'], 'Desenho de gibi', [0, 1]],
    ['menu', 'MENU', ['ME', 'NU'], 'Desenho de menu', [0, 1]],
    ['laca', 'LACA', ['LA', 'CA'], 'Desenho de laca', [0, 1]],
    ['mimo', 'MIMO', ['MI', 'MO'], 'Desenho de mimo', [0, 1]],
    ['sela', 'SELA', ['SE', 'LA'], 'Desenho de sela', [0, 1]],
    ['tina', 'TINA', ['TI', 'NA'], 'Desenho de tina', [0, 1]],
    ['fato', 'FATO', ['FA', 'TO'], 'Desenho de fato', [0, 1]],
    ['bula', 'BULA', ['BU', 'LA'], 'Desenho de bula', [0, 1]],
    ['tofu', 'TOFU', ['TO', 'FU'], 'Desenho de tofu', [0, 1]],
    ['gole', 'GOLE', ['GO', 'LE'], 'Desenho de gole', [0, 1]],
    ['pita', 'PITA', ['PI', 'TA'], 'Desenho de pita', [0, 1]],
    ['juta', 'JUTA', ['JU', 'TA'], 'Desenho de juta', [0, 1]],
    ['lava', 'LAVA', ['LA', 'VA'], 'Desenho de lava', [0, 1]],
    ['teca', 'TECA', ['TE', 'CA'], 'Desenho de teca', [0, 1]],
    ['cume', 'CUME', ['CU', 'ME'], 'Desenho de cume', [0, 1]],
    ['lapa', 'LAPA', ['LA', 'PA'], 'Desenho de lapa', [0, 1]],
    ['rama', 'RAMA', ['RA', 'MA'], 'Desenho de rama', [0, 1]],
    ['coro', 'CORO', ['CO', 'RO'], 'Desenho de coro', [0, 1]],
    ['gala', 'GALA', ['GA', 'LA'], 'Desenho de gala', [0, 1]],
    ['lote', 'LOTE', ['LO', 'TE'], 'Desenho de lote', [0, 1]],
    ['boga', 'BOGA', ['BO', 'GA'], 'Desenho de boga', [0, 1]],
    ['pacu', 'PACU', ['PA', 'CU'], 'Desenho de pacu', [0, 1]],
    ['paru', 'PARU', ['PA', 'RU'], 'Desenho de paru', [0, 1]],
    ['mero', 'MERO', ['ME', 'RO'], 'Desenho de mero', [0, 1]],
    ['biga', 'BIGA', ['BI', 'GA'], 'Desenho de biga', [0, 1]],
    ['neta', 'NETA', ['NE', 'TA'], 'Desenho de neta', [0, 1]],
    ['bico', 'BICO', ['BI', 'CO'], 'Desenho de bico', [0, 1]],
    ['menino', 'MENINO', ['ME', 'NI', 'NO'], 'Desenho de menino', [2]],
    ['menina', 'MENINA', ['ME', 'NI', 'NA'], 'Desenho de menina', [2]],
    ['garoto', 'GAROTO', ['GA', 'RO', 'TO'], 'Desenho de garoto', [2]],
    ['garota', 'GAROTA', ['GA', 'RO', 'TA'], 'Desenho de garota', [2]],
    ['piloto', 'PILOTO', ['PI', 'LO', 'TO'], 'Desenho de piloto', [2]],
    ['marujo', 'MARUJO', ['MA', 'RU', 'JO'], 'Desenho de marujo', [2]],
    ['boneco', 'BONECO', ['BO', 'NE', 'CO'], 'Desenho de boneco', [2]],
    ['gorila', 'GORILA', ['GO', 'RI', 'LA'], 'Desenho de gorila', [2]],
    ['javali', 'JAVALI', ['JA', 'VA', 'LI'], 'Desenho de javali', [2]],
    ['mamute', 'MAMUTE', ['MA', 'MU', 'TE'], 'Desenho de mamute', [2]],
    ['camelo', 'CAMELO', ['CA', 'ME', 'LO'], 'Desenho de camelo', [2]],
    ['cadela', 'CADELA', ['CA', 'DE', 'LA'], 'Desenho de cadela', [2]],
    ['tucano', 'TUCANO', ['TU', 'CA', 'NO'], 'Desenho de tucano', [2]],
    ['coruja', 'CORUJA', ['CO', 'RU', 'JA'], 'Desenho de coruja', [2]],
    ['jaburu', 'JABURU', ['JA', 'BU', 'RU'], 'Desenho de jaburu', [2]],
    ['robalo', 'ROBALO', ['RO', 'BA', 'LO'], 'Desenho de robalo', [2]],
    ['cavala', 'CAVALA', ['CA', 'VA', 'LA'], 'Desenho de cavala', [2]],
    ['barata', 'BARATA', ['BA', 'RA', 'TA'], 'Desenho de barata', [2]],
    ['comida', 'COMIDA', ['CO', 'MI', 'DA'], 'Desenho de comida', [2]],
    ['farofa', 'FAROFA', ['FA', 'RO', 'FA'], 'Desenho de farofa', [2]],
    ['jujuba', 'JUJUBA', ['JU', 'JU', 'BA'], 'Desenho de jujuba', [2]],
    ['salada', 'SALADA', ['SA', 'LA', 'DA'], 'Desenho de salada', [2]],
    ['cocada', 'COCADA', ['CO', 'CA', 'DA'], 'Desenho de cocada', [2]],
    ['risoto', 'RISOTO', ['RI', 'SO', 'TO'], 'Desenho de risoto', [2]],
    ['ricota', 'RICOTA', ['RI', 'CO', 'TA'], 'Desenho de ricota', [2]],
    ['melado', 'MELADO', ['ME', 'LA', 'DO'], 'Desenho de melado', [2]],
    ['garapa', 'GARAPA', ['GA', 'RA', 'PA'], 'Desenho de garapa', [2]],
    ['cevada', 'CEVADA', ['CE', 'VA', 'DA'], 'Desenho de cevada', [2]],
    ['romero', 'ROMERO', ['RO', 'ME', 'RO'], 'Desenho de romero', [2]],
    ['pepino', 'PEPINO', ['PE', 'PI', 'NO'], 'Desenho de pepino', [2]],
    ['salame', 'SALAME', ['SA', 'LA', 'ME'], 'Desenho de salame', [2]],
    ['cereja', 'CEREJA', ['CE', 'RE', 'JA'], 'Desenho de cereja', [2]],
    ['canela', 'CANELA', ['CA', 'NE', 'LA'], 'Desenho de canela', [2]],
    ['caneca', 'CANECA', ['CA', 'NE', 'CA'], 'Desenho de caneca', [2]],
    ['bebida', 'BEBIDA', ['BE', 'BI', 'DA'], 'Desenho de bebida', [2]],
    ['cabelo', 'CABELO', ['CA', 'BE', 'LO'], 'Desenho de cabelo', [2]],
    ['bigode', 'BIGODE', ['BI', 'GO', 'DE'], 'Desenho de bigode', [2]],
    ['parede', 'PAREDE', ['PA', 'RE', 'DE'], 'Desenho de parede', [2]],
    ['gaveta', 'GAVETA', ['GA', 'VE', 'TA'], 'Desenho de gaveta', [2]],
    ['tomada', 'TOMADA', ['TO', 'MA', 'DA'], 'Desenho de tomada', [2]],
    ['tapete', 'TAPETE', ['TA', 'PE', 'TE'], 'Desenho de tapete', [2]],
    ['tijolo', 'TIJOLO', ['TI', 'JO', 'LO'], 'Desenho de tijolo', [2]],
    ['palito', 'PALITO', ['PA', 'LI', 'TO'], 'Desenho de palito', [2]],
    ['canudo', 'CANUDO', ['CA', 'NU', 'DO'], 'Desenho de canudo', [2]],
    ['fivela', 'FIVELA', ['FI', 'VE', 'LA'], 'Desenho de fivela', [2]],
    ['muleta', 'MULETA', ['MU', 'LE', 'TA'], 'Desenho de muleta', [2]],
    ['pomada', 'POMADA', ['PO', 'MA', 'DA'], 'Desenho de pomada', [2]],
    ['vacina', 'VACINA', ['VA', 'CI', 'NA'], 'Desenho de vacina', [2]],
    ['sucata', 'SUCATA', ['SU', 'CA', 'TA'], 'Desenho de sucata', [2]],
    ['sacola', 'SACOLA', ['SA', 'CO', 'LA'], 'Desenho de sacola', [2]],
    ['tigela', 'TIGELA', ['TI', 'GE', 'LA'], 'Desenho de tigela', [2]],
    ['tabela', 'TABELA', ['TA', 'BE', 'LA'], 'Desenho de tabela', [2]],
    ['tecido', 'TECIDO', ['TE', 'CI', 'DO'], 'Desenho de tecido', [2]],
    ['cabide', 'CABIDE', ['CA', 'BI', 'DE'], 'Desenho de cabide', [2]],
    ['buraco', 'BURACO', ['BU', 'RA', 'CO'], 'Desenho de buraco', [2]],
    ['camada', 'CAMADA', ['CA', 'MA', 'DA'], 'Desenho de camada', [2]],
    ['careta', 'CARETA', ['CA', 'RE', 'TA'], 'Desenho de careta', [2]],
    ['cinema', 'CINEMA', ['CI', 'NE', 'MA'], 'Desenho de cinema', [2]],
    ['capela', 'CAPELA', ['CA', 'PE', 'LA'], 'Desenho de capela', [2]],
    ['coluna', 'COLUNA', ['CO', 'LU', 'NA'], 'Desenho de coluna', [2]],
    ['novelo', 'NOVELO', ['NO', 'VE', 'LO'], 'Desenho de novelo', [2]],
    ['pacote', 'PACOTE', ['PA', 'CO', 'TE'], 'Desenho de pacote', [2]],
    ['cometa', 'COMETA', ['CO', 'ME', 'TA'], 'Desenho de cometa', [2]],
    ['cabana', 'CABANA', ['CA', 'BA', 'NA'], 'Desenho de cabana', [2]],
    ['maleta', 'MALETA', ['MA', 'LE', 'TA'], 'Desenho de maleta', [2]],
    ['casulo', 'CASULO', ['CA', 'SU', 'LO'], 'Desenho de casulo', [2]],
    ['manada', 'MANADA', ['MA', 'NA', 'DA'], 'Desenho de manada', [2]],
    ['narina', 'NARINA', ['NA', 'RI', 'NA'], 'Desenho de narina', [2]],
    ['pegada', 'PEGADA', ['PE', 'GA', 'DA'], 'Desenho de pegada', [2]],
    ['topete', 'TOPETE', ['TO', 'PE', 'TE'], 'Desenho de topete', [2]],
    ['tulipa', 'TULIPA', ['TU', 'LI', 'PA'], 'Desenho de tulipa', [2]],
    ['veludo', 'VELUDO', ['VE', 'LU', 'DO'], 'Desenho de veludo', [2]],
    ['vareta', 'VARETA', ['VA', 'RE', 'TA'], 'Desenho de vareta', [2]],
    ['valeta', 'VALETA', ['VA', 'LE', 'TA'], 'Desenho de valeta', [2]],
    ['bolota', 'BOLOTA', ['BO', 'LO', 'TA'], 'Desenho de bolota', [2]],
    ['botina', 'BOTINA', ['BO', 'TI', 'NA'], 'Desenho de botina', [2]],
    ['cururu', 'CURURU', ['CU', 'RU', 'RU'], 'Desenho de cururu', [2]],
    ['galope', 'GALOPE', ['GA', 'LO', 'PE'], 'Desenho de galope', [2]],
    ['gelado', 'GELADO', ['GE', 'LA', 'DO'], 'Desenho de gelado', [2]],
    ['peruca', 'PERUCA', ['PE', 'RU', 'CA'], 'Desenho de peruca', [2]],
    ['colete', 'COLETE', ['CO', 'LE', 'TE'], 'Desenho de colete', [2]],
    ['picape', 'PICAPE', ['PI', 'CA', 'PE'], 'Desenho de picape', [2]],
    ['recado', 'RECADO', ['RE', 'CA', 'DO'], 'Desenho de recado', [2]],
    ['redoma', 'REDOMA', ['RE', 'DO', 'MA'], 'Desenho de redoma', [2]],
    ['regata', 'REGATA', ['RE', 'GA', 'TA'], 'Desenho de regata', [2]],
    ['remada', 'REMADA', ['RE', 'MA', 'DA'], 'Desenho de remada', [2]],
    ['safira', 'SAFIRA', ['SA', 'FI', 'RA'], 'Desenho de safira', [2]],
    ['sereno', 'SERENO', ['SE', 'RE', 'NO'], 'Desenho de sereno', [2]],
    ['sineta', 'SINETA', ['SI', 'NE', 'TA'], 'Desenho de sineta', [2]],
    ['sirene', 'SIRENE', ['SI', 'RE', 'NE'], 'Desenho de sirene', [2]],
    ['soneca', 'SONECA', ['SO', 'NE', 'CA'], 'Desenho de soneca', [2]],
    ['savana', 'SAVANA', ['SA', 'VA', 'NA'], 'Desenho de savana', [2]],
    ['laguna', 'LAGUNA', ['LA', 'GU', 'NA'], 'Desenho de laguna', [2]],
    ['cadete', 'CADETE', ['CA', 'DE', 'TE'], 'Desenho de cadete', [2]],
    ['girino', 'GIRINO', ['GI', 'RI', 'NO'], 'Desenho de girino', [2]],
    ['beluga', 'BELUGA', ['BE', 'LU', 'GA'], 'Desenho de beluga', [2]],
    ['rapina', 'RAPINA', ['RA', 'PI', 'NA'], 'Desenho de rapina', [2]],
    ['bacaba', 'BACABA', ['BA', 'CA', 'BA'], 'Desenho de bacaba', [2]],
    ['badalo', 'BADALO', ['BA', 'DA', 'LO'], 'Desenho de badalo', [2]],
    ['babado', 'BABADO', ['BA', 'BA', 'DO'], 'Desenho de babado', [2]],
    ['betume', 'BETUME', ['BE', 'TU', 'ME'], 'Desenho de betume', [2]],
    ['filete', 'FILETE', ['FI', 'LE', 'TE'], 'Desenho de filete', [2]],
    ['pepita', 'PEPITA', ['PE', 'PI', 'TA'], 'Desenho de pepita', [2]],
    ['rabada', 'RABADA', ['RA', 'BA', 'DA'], 'Desenho de rabada', [2]],
    ['farelo', 'FARELO', ['FA', 'RE', 'LO'], 'Desenho de farelo', [3]],
    ['bacuri', 'BACURI', ['BA', 'CU', 'RI'], 'Desenho de bacuri', [3]],
    ['bicama', 'BICAMA', ['BI', 'CA', 'MA'], 'Desenho de bicama', [3]],
    ['boleto', 'BOLETO', ['BO', 'LE', 'TO'], 'Desenho de boleto', [3]],
    ['botija', 'BOTIJA', ['BO', 'TI', 'JA'], 'Desenho de botija', [3]],
    ['calota', 'CALOTA', ['CA', 'LO', 'TA'], 'Desenho de calota', [3]],
    ['capote', 'CAPOTE', ['CA', 'PO', 'TE'], 'Desenho de capote', [3]],
    ['caruru', 'CARURU', ['CA', 'RU', 'RU'], 'Desenho de caruru', [3]],
    ['coreto', 'CORETO', ['CO', 'RE', 'TO'], 'Desenho de coreto', [3]],
    ['jaleco', 'JALECO', ['JA', 'LE', 'CO'], 'Desenho de jaleco', [3]],
    ['lapela', 'LAPELA', ['LA', 'PE', 'LA'], 'Desenho de lapela', [3]],
    ['lavabo', 'LAVABO', ['LA', 'VA', 'BO'], 'Desenho de lavabo', [3]],
    ['malote', 'MALOTE', ['MA', 'LO', 'TE'], 'Desenho de malote', [3]],
    ['matuto', 'MATUTO', ['MA', 'TU', 'TO'], 'Desenho de matuto', [3]],
    ['mimosa', 'MIMOSA', ['MI', 'MO', 'SA'], 'Desenho de mimosa', [3]],
    ['murici', 'MURICI', ['MU', 'RI', 'CI'], 'Desenho de murici', [3]],
    ['pagode', 'PAGODE', ['PA', 'GO', 'DE'], 'Desenho de pagode', [3]],
    ['patada', 'PATADA', ['PA', 'TA', 'DA'], 'Desenho de patada', [3]],
    ['pelota', 'PELOTA', ['PE', 'LO', 'TA'], 'Desenho de pelota', [3]],
    ['pisada', 'PISADA', ['PI', 'SA', 'DA'], 'Desenho de pisada', [3]],
    ['reboco', 'REBOCO', ['RE', 'BO', 'CO'], 'Desenho de reboco', [3]],
    ['roleta', 'ROLETA', ['RO', 'LE', 'TA'], 'Desenho de roleta', [3]],
    ['sabugo', 'SABUGO', ['SA', 'BU', 'GO'], 'Desenho de sabugo', [3]],
    ['tapera', 'TAPERA', ['TA', 'PE', 'RA'], 'Desenho de tapera', [3]],
    ['vitelo', 'VITELO', ['VI', 'TE', 'LO'], 'Desenho de vitelo', [3]],
    ['batina', 'BATINA', ['BA', 'TI', 'NA'], 'Desenho de batina', [3]],
    ['batuta', 'BATUTA', ['BA', 'TU', 'TA'], 'Desenho de batuta', [3]],
    ['cajado', 'CAJADO', ['CA', 'JA', 'DO'], 'Desenho de cajado', [3]],
    ['casaca', 'CASACA', ['CA', 'SA', 'CA'], 'Desenho de casaca', [3]],
    ['cerume', 'CERUME', ['CE', 'RU', 'ME'], 'Desenho de cerume', [3]],
    ['figura', 'FIGURA', ['FI', 'GU', 'RA'], 'Desenho de figura', [3]],
    ['luneta', 'LUNETA', ['LU', 'NE', 'TA'], 'Desenho de luneta', [3]],
    ['papiro', 'PAPIRO', ['PA', 'PI', 'RO'], 'Desenho de papiro', [3]],
    ['pupila', 'PUPILA', ['PU', 'PI', 'LA'], 'Desenho de pupila', [3]],
    ['sinuca', 'SINUCA', ['SI', 'NU', 'CA'], 'Desenho de sinuca', [3]],
    ['penico', 'PENICO', ['PE', 'NI', 'CO'], 'Desenho de penico', [3]],
    ['bobina', 'BOBINA', ['BO', 'BI', 'NA'], 'Desenho de bobina', [3]],
    ['vitela', 'VITELA', ['VI', 'TE', 'LA'], 'Desenho de vitela', [3]],
    ['bovina', 'BOVINA', ['BO', 'VI', 'NA'], 'Desenho de bovina', [3]],
    ['gasosa', 'GASOSA', ['GA', 'SO', 'SA'], 'Desenho de gasosa', [3]],
    ['paleta', 'PALETA', ['PA', 'LE', 'TA'], 'Desenho de paleta', [3]],
    ['gemada', 'GEMADA', ['GE', 'MA', 'DA'], 'Desenho de gemada', [3]],
    ['remoto', 'REMOTO', ['RE', 'MO', 'TO'], 'Desenho de remoto', [3]],
    ['biruta', 'BIRUTA', ['BI', 'RU', 'TA'], 'Desenho de biruta', [3]],
    ['fedora', 'FEDORA', ['FE', 'DO', 'RA'], 'Desenho de fedora', [3]],
    ['cabina', 'CABINA', ['CA', 'BI', 'NA'], 'Desenho de cabina', [3]],
    ['bovino', 'BOVINO', ['BO', 'VI', 'NO'], 'Desenho de bovino', [3]],
    ['motora', 'MOTORA', ['MO', 'TO', 'RA'], 'Desenho de motora', [3]],
    ['bodega', 'BODEGA', ['BO', 'DE', 'GA'], 'Desenho de bodega', [3]],
    ['bocado', 'BOCADO', ['BO', 'CA', 'DO'], 'Desenho de bocado', [3]],
    ['subida', 'SUBIDA', ['SU', 'BI', 'DA'], 'Desenho de subida', [3]],
    ['resina', 'RESINA', ['RE', 'SI', 'NA'], 'Desenho de resina', [3]],
    ['picada', 'PICADA', ['PI', 'CA', 'DA'], 'Desenho de picada', [3]],
    ['galera', 'GALERA', ['GA', 'LE', 'RA'], 'Desenho de galera', [3]],
    ['colina', 'COLINA', ['CO', 'LI', 'NA'], 'Desenho de colina', [3]],
    ['recibo', 'RECIBO', ['RE', 'CI', 'BO'], 'Desenho de recibo', [3]],
    ['tatame', 'TATAME', ['TA', 'TA', 'ME'], 'Desenho de tatame', [3]],
    ['cacifo', 'CACIFO', ['CA', 'CI', 'FO'], 'Desenho de cacifo', [3]],
    ['pataca', 'PATACA', ['PA', 'TA', 'CA'], 'Desenho de pataca', [3]],
    ['caneco', 'CANECO', ['CA', 'NE', 'CO'], 'Desenho de caneco', [3]],
    ['gamela', 'GAMELA', ['GA', 'ME', 'LA'], 'Desenho de gamela', [3]],
    ['mesada', 'MESADA', ['ME', 'SA', 'DA'], 'Desenho de mesada', [3]],
    ['novela', 'NOVELA', ['NO', 'VE', 'LA'], 'Desenho de novela', [3]],
    ['pomelo', 'POMELO', ['PO', 'ME', 'LO'], 'Desenho de pomelo', [3]],
    ['rolete', 'ROLETE', ['RO', 'LE', 'TE'], 'Desenho de rolete', [3]],
    ['rodela', 'RODELA', ['RO', 'DE', 'LA'], 'Desenho de rodela', [3]],
    ['figada', 'FIGADA', ['FI', 'GA', 'DA'], 'Desenho de figada', [3]],
    ['perada', 'PERADA', ['PE', 'RA', 'DA'], 'Desenho de perada', [3]],
    ['pacova', 'PACOVA', ['PA', 'CO', 'VA'], 'Desenho de pacova', [3]],
    ['sapoti', 'SAPOTI', ['SA', 'PO', 'TI'], 'Desenho de sapoti', [3]],
    ['tucupi', 'TUCUPI', ['TU', 'CU', 'PI'], 'Desenho de tucupi', [3]],
    ['pevide', 'PEVIDE', ['PE', 'VI', 'DE'], 'Desenho de pevide', [3]],
    ['peroba', 'PEROBA', ['PE', 'RO', 'BA'], 'Desenho de peroba', [3]],
    ['virola', 'VIROLA', ['VI', 'RO', 'LA'], 'Desenho de virola', [3]],
    ['vereda', 'VEREDA', ['VE', 'RE', 'DA'], 'Desenho de vereda', [3]],
    ['ravina', 'RAVINA', ['RA', 'VI', 'NA'], 'Desenho de ravina', [3]],
    ['maraca', 'MARACA', ['MA', 'RA', 'CA'], 'Desenho de maraca', [3]],
    ['bolero', 'BOLERO', ['BO', 'LE', 'RO'], 'Desenho de bolero', [3]],
    ['rabeca', 'RABECA', ['RA', 'BE', 'CA'], 'Desenho de rabeca', [3]],
    ['sacada', 'SACADA', ['SA', 'CA', 'DA'], 'Desenho de sacada', [3]],
    ['morada', 'MORADA', ['MO', 'RA', 'DA'], 'Desenho de morada', [3]],
    ['badejo', 'BADEJO', ['BA', 'DE', 'JO'], 'Desenho de badejo', [3]],
    ['parati', 'PARATI', ['PA', 'RA', 'TI'], 'Desenho de parati', [3]],
    ['bicuda', 'BICUDA', ['BI', 'CU', 'DA'], 'Desenho de bicuda', [3]],
    ['betara', 'BETARA', ['BE', 'TA', 'RA'], 'Desenho de betara', [3]],
    ['salema', 'SALEMA', ['SA', 'LE', 'MA'], 'Desenho de salema', [3]],
    ['tuvira', 'TUVIRA', ['TU', 'VI', 'RA'], 'Desenho de tuvira', [3]],
    ['motoca', 'MOTOCA', ['MO', 'TO', 'CA'], 'Desenho de motoca', [3]],
    ['piroga', 'PIROGA', ['PI', 'RO', 'GA'], 'Desenho de piroga', [3]],
    ['jabuti', 'JABUTI', ['JA', 'BU', 'TI'], 'Desenho de jabuti', [3]],
    ['raposa', 'RAPOSA', ['RA', 'PO', 'SA'], 'Desenho de raposa', [3]],
    ['tapiti', 'TAPITI', ['TA', 'PI', 'TI'], 'Desenho de tapiti', [3]],
    ['cateto', 'CATETO', ['CA', 'TE', 'TO'], 'Desenho de cateto', [3]],
    ['pipira', 'PIPIRA', ['PI', 'PI', 'RA'], 'Desenho de pipira', [3]],
    ['pijama', 'PIJAMA', ['PI', 'JA', 'MA'], 'Desenho de pijama', [3]],
    ['casaco', 'CASACO', ['CA', 'SA', 'CO'], 'Desenho de casaco', [3]],
    ['rebeca', 'REBECA', ['RE', 'BE', 'CA'], 'Desenho de rebeca', [3]],
    ['japona', 'JAPONA', ['JA', 'PO', 'NA'], 'Desenho de japona', [3]],
    ['pirata', 'PIRATA', ['PI', 'RA', 'TA'], 'Desenho de pirata', [3]],
    ['judoca', 'JUDOCA', ['JU', 'DO', 'CA'], 'Desenho de judoca', [3]],
    ['gilete', 'GILETE', ['GI', 'LE', 'TE'], 'Desenho de gilete', [3]],
    ['medula', 'MEDULA', ['ME', 'DU', 'LA'], 'Desenho de medula', [3]],
    ['garupa', 'GARUPA', ['GA', 'RU', 'PA'], 'Desenho de garupa', [3]],
    ['risada', 'RISADA', ['RI', 'SA', 'DA'], 'Desenho de risada', [3]],
    ['capivara', 'CAPIVARA', ['CA', 'PI', 'VA', 'RA'], 'Desenho de capivara', [4]],
    ['perereca', 'PERERECA', ['PE', 'RE', 'RE', 'CA'], 'Desenho de perereca', [4]],
    ['vagalume', 'VAGALUME', ['VA', 'GA', 'LU', 'ME'], 'Desenho de vagalume', [4]],
    ['mariposa', 'MARIPOSA', ['MA', 'RI', 'PO', 'SA'], 'Desenho de mariposa', [4]],
    ['pelicano', 'PELICANO', ['PE', 'LI', 'CA', 'NO'], 'Desenho de pelicano', [4]],
    ['pirarucu', 'PIRARUCU', ['PI', 'RA', 'RU', 'CU'], 'Desenho de pirarucu', [4]],
    ['serelepe', 'SERELEPE', ['SE', 'RE', 'LE', 'PE'], 'Desenho de serelepe', [4]],
    ['caramujo', 'CARAMUJO', ['CA', 'RA', 'MU', 'JO'], 'Desenho de caramujo', [4]],
    ['pirulito', 'PIRULITO', ['PI', 'RU', 'LI', 'TO'], 'Desenho de pirulito', [4]],
    ['caramelo', 'CARAMELO', ['CA', 'RA', 'ME', 'LO'], 'Desenho de caramelo', [4]],
    ['limonada', 'LIMONADA', ['LI', 'MO', 'NA', 'DA'], 'Desenho de limonada', [4]],
    ['vitamina', 'VITAMINA', ['VI', 'TA', 'MI', 'NA'], 'Desenho de vitamina', [4]],
    ['gelatina', 'GELATINA', ['GE', 'LA', 'TI', 'NA'], 'Desenho de gelatina', [4]],
    ['rapadura', 'RAPADURA', ['RA', 'PA', 'DU', 'RA'], 'Desenho de rapadura', [4]],
    ['cogumelo', 'COGUMELO', ['CO', 'GU', 'ME', 'LO'], 'Desenho de cogumelo', [4]],
    ['rabanete', 'RABANETE', ['RA', 'BA', 'NE', 'TE'], 'Desenho de rabanete', [4]],
    ['camomila', 'CAMOMILA', ['CA', 'MO', 'MI', 'LA'], 'Desenho de camomila', [4]],
    ['panetone', 'PANETONE', ['PA', 'NE', 'TO', 'NE'], 'Desenho de panetone', [4]],
    ['bananada', 'BANANADA', ['BA', 'NA', 'NA', 'DA'], 'Desenho de bananada', [4]],
    ['gororoba', 'GOROROBA', ['GO', 'RO', 'RO', 'BA'], 'Desenho de gororoba', [4]],
    ['tiramisu', 'TIRAMISU', ['TI', 'RA', 'MI', 'SU'], 'Desenho de tiramisu', [4]],
    ['madalena', 'MADALENA', ['MA', 'DA', 'LE', 'NA'], 'Desenho de madalena', [4]],
    ['panelada', 'PANELADA', ['PA', 'NE', 'LA', 'DA'], 'Desenho de panelada', [4]],
    ['telefone', 'TELEFONE', ['TE', 'LE', 'FO', 'NE'], 'Desenho de telefone', [4]],
    ['camiseta', 'CAMISETA', ['CA', 'MI', 'SE', 'TA'], 'Desenho de camiseta', [4]],
    ['gabinete', 'GABINETE', ['GA', 'BI', 'NE', 'TE'], 'Desenho de gabinete', [4]],
    ['capacete', 'CAPACETE', ['CA', 'PA', 'CE', 'TE'], 'Desenho de capacete', [4]],
    ['parafuso', 'PARAFUSO', ['PA', 'RA', 'FU', 'SO'], 'Desenho de parafuso', [4]],
    ['sabonete', 'SABONETE', ['SA', 'BO', 'NE', 'TE'], 'Desenho de sabonete', [4]],
    ['cotovelo', 'COTOVELO', ['CO', 'TO', 'VE', 'LO'], 'Desenho de cotovelo', [4]],
    ['camisola', 'CAMISOLA', ['CA', 'MI', 'SO', 'LA'], 'Desenho de camisola', [4]],
    ['curativo', 'CURATIVO', ['CU', 'RA', 'TI', 'VO'], 'Desenho de curativo', [4]],
    ['cotonete', 'COTONETE', ['CO', 'TO', 'NE', 'TE'], 'Desenho de cotonete', [4]],
    ['canivete', 'CANIVETE', ['CA', 'NI', 'VE', 'TE'], 'Desenho de canivete', [4]],
    ['megafone', 'MEGAFONE', ['ME', 'GA', 'FO', 'NE'], 'Desenho de megafone', [4]],
    ['cavalete', 'CAVALETE', ['CA', 'VA', 'LE', 'TE'], 'Desenho de cavalete', [4]],
    ['secadora', 'SECADORA', ['SE', 'CA', 'DO', 'RA'], 'Desenho de secadora', [4]],
    ['gasolina', 'GASOLINA', ['GA', 'SO', 'LI', 'NA'], 'Desenho de gasolina', [4]],
    ['catarata', 'CATARATA', ['CA', 'TA', 'RA', 'TA'], 'Desenho de catarata', [4]],
    ['picareta', 'PICARETA', ['PI', 'CA', 'RE', 'TA'], 'Desenho de picareta', [4]],
    ['serenata', 'SERENATA', ['SE', 'RE', 'NA', 'TA'], 'Desenho de serenata', [5]],
    ['caravana', 'CARAVANA', ['CA', 'RA', 'VA', 'NA'], 'Desenho de caravana', [5]],
    ['limusine', 'LIMUSINE', ['LI', 'MU', 'SI', 'NE'], 'Desenho de limusine', [5]],
    ['manicure', 'MANICURE', ['MA', 'NI', 'CU', 'RE'], 'Desenho de manicure', [5]],
    ['pedicure', 'PEDICURE', ['PE', 'DI', 'CU', 'RE'], 'Desenho de pedicure', [5]],
    ['figurino', 'FIGURINO', ['FI', 'GU', 'RI', 'NO'], 'Desenho de figurino', [5]],
    ['vilarejo', 'VILAREJO', ['VI', 'LA', 'RE', 'JO'], 'Desenho de vilarejo', [5]],
    ['camarote', 'CAMAROTE', ['CA', 'MA', 'RO', 'TE'], 'Desenho de camarote', [5]],
    ['celofane', 'CELOFANE', ['CE', 'LO', 'FA', 'NE'], 'Desenho de celofane', [5]],
    ['patinete', 'PATINETE', ['PA', 'TI', 'NE', 'TE'], 'Desenho de patinete', [5]],
    ['detetive', 'DETETIVE', ['DE', 'TE', 'TI', 'VE'], 'Desenho de detetive', [5]],
    ['rabanada', 'RABANADA', ['RA', 'BA', 'NA', 'DA'], 'Desenho de rabanada', [5]],
    ['calamari', 'CALAMARI', ['CA', 'LA', 'MA', 'RI'], 'Desenho de calamari', [5]],
    ['levedura', 'LEVEDURA', ['LE', 'VE', 'DU', 'RA'], 'Desenho de levedura', [5]],
    ['medicina', 'MEDICINA', ['ME', 'DI', 'CI', 'NA'], 'Desenho de medicina', [5]],
    ['papelada', 'PAPELADA', ['PA', 'PE', 'LA', 'DA'], 'Desenho de papelada', [5]],
    ['lavadora', 'LAVADORA', ['LA', 'VA', 'DO', 'RA'], 'Desenho de lavadora', [5]],
    ['manivela', 'MANIVELA', ['MA', 'NI', 'VE', 'LA'], 'Desenho de manivela', [5]],
    ['vaselina', 'VASELINA', ['VA', 'SE', 'LI', 'NA'], 'Desenho de vaselina', [5]],
    ['parafina', 'PARAFINA', ['PA', 'RA', 'FI', 'NA'], 'Desenho de parafina', [5]],
    ['silicone', 'SILICONE', ['SI', 'LI', 'CO', 'NE'], 'Desenho de silicone', [5]],
    ['cidadela', 'CIDADELA', ['CI', 'DA', 'DE', 'LA'], 'Desenho de cidadela', [5]],
    ['celulose', 'CELULOSE', ['CE', 'LU', 'LO', 'SE'], 'Desenho de celulose', [5]],
    ['gasoduto', 'GASODUTO', ['GA', 'SO', 'DU', 'TO'], 'Desenho de gasoduto', [5]],
    ['jogadora', 'JOGADORA', ['JO', 'GA', 'DO', 'RA'], 'Desenho de jogadora', [5]],
    ['lutadora', 'LUTADORA', ['LU', 'TA', 'DO', 'RA'], 'Desenho de lutadora', [5]],
    ['nadadora', 'NADADORA', ['NA', 'DA', 'DO', 'RA'], 'Desenho de nadadora', [5]],
    ['canaleta', 'CANALETA', ['CA', 'NA', 'LE', 'TA'], 'Desenho de canaleta', [5]],
    ['milanesa', 'MILANESA', ['MI', 'LA', 'NE', 'SA'], 'Desenho de milanesa', [5]],
    ['gabiroba', 'GABIROBA', ['GA', 'BI', 'RO', 'BA'], 'Desenho de gabiroba', [5]],
    ['cabidela', 'CABIDELA', ['CA', 'BI', 'DE', 'LA'], 'Desenho de cabidela', [5]],
    ['ceboleta', 'CEBOLETA', ['CE', 'BO', 'LE', 'TA'], 'Desenho de ceboleta', [5]],
    ['demerara', 'DEMERARA', ['DE', 'ME', 'RA', 'RA'], 'Desenho de demerara', [5]],
    ['sucupira', 'SUCUPIRA', ['SU', 'CU', 'PI', 'RA'], 'Desenho de sucupira', [5]],
    ['camareta', 'CAMARETA', ['CA', 'MA', 'RE', 'TA'], 'Desenho de camareta', [5]],
    ['pirarara', 'PIRARARA', ['PI', 'RA', 'RA', 'RA'], 'Desenho de pirarara', [5]],
    ['sororoca', 'SOROROCA', ['SO', 'RO', 'RO', 'CA'], 'Desenho de sororoca', [5]],
    ['coridora', 'CORIDORA', ['CO', 'RI', 'DO', 'RA'], 'Desenho de coridora', [5]],
    ['caravela', 'CARAVELA', ['CA', 'RA', 'VE', 'LA'], 'Desenho de caravela', [5]],
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = extras;
  else root.SilabasLexicon = extras;
})(typeof window !== 'undefined' ? window : globalThis);
